source 'http://rubygems.org'


gem "pry"
gem "wally"
gem "nokogiri"
gem "require_all"
gem "cucumber"
gem "i18n"
gem "chronic"
gem "addressable"
gem "selenium-webdriver", "2.40.0"
gem "json"
gem "rest-client"
gem "rspec-expectations", "3.0.0"
gem "frank-cucumber"
gem "unicode"
gem "appium_lib"
gem "rspec", "3.0.0"
gem "humanize"
