source 'http://rubygems.org'


gem "i18n"
gem "chronic"
gem "addressable"
gem "selenium-webdriver", "2.40.0"
gem "cucumber", "1.3.15"
gem "json"
gem "rest-client"
gem "rspec-expectations", "3.0.0"
gem "frank-cucumber"
gem "nokogiri", "1.6.0"
gem "unicode"
gem "appium_lib"
gem "rspec", "3.0.0"
gem "humanize"
gem "wally"
gem "pry"
gem "require_all"
gem "encryptor"
